## Import Module

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
from xgboost import XGBClassifier
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split

## Data Load

In [3]:
ispu_2023 = pd.read_csv('./ISPU/data-indeks-standar-pencemar-udara-(ispu)-di-provinsi-dki-jakarta-2023-komponen-data.csv')
ispu_2024 = pd.read_csv('./ISPU/data-indeks-standar-pencemar-udara-(ispu)-di-provinsi-dki-jakarta-komponen-data-2024.csv')
ispu_2025 = pd.read_csv('./ISPU/data-indeks-standar-pencemar-udara-(ispu)-di-provinsi-dki-jakarta-komponen-data-2025.csv')

In [4]:
ispu_2023

,periode_data,tanggal,stasiun,pm_sepuluh,pm_duakomalima,sulfur_dioksida,karbon_monoksida,ozon,nitrogen_dioksida,max,parameter_pencemar_kritis,kategori
0,202302,2023-02-25,DKI5 Kebon Jeruk Jakarta Barat,35,-,13,12,31,18,35,PM10,BAIK
1,202302,2023-02-26,DKI5 Kebon Jeruk Jakarta Barat,23,-,14,9,32,11,32,O3,BAIK
2,202302,2023-02-27,DKI5 Kebon Jeruk Jakarta Barat,20,-,13,8,33,13,33,O3,BAIK
3,202302,2023-02-28,DKI5 Kebon Jeruk Jakarta Barat,30,-,21,11,28,18,30,PM10,BAIK
4,202303,2023-03-01,DKI1 Bunderan HI,38,44,50,8,19,27,50,3,BAIK
...,...,...,...,...,...,...,...,...,...,...,...,...
1820,202311,2023-11-26,DKI5 Kebon Jeruk,48,71,33,21,44,20,71,PM25,SEDANG
1821,202311,2023-11-27,DKI5 Kebon Jeruk,51,76,32,18,53,19,76,PM25,SEDANG
1822,202311,2023-11-28,DKI5 Kebon Jeruk,56,88,33,20,48,21,88,PM25,SEDANG
1823,202311,2023-11-29,DKI5 Kebon Jeruk,56,88,32,18,56,18,88,PM25,SEDANG
1824,202311,2023-11-30,DKI5 Kebon Jeruk,30,57,32,15,61,17,61,O3,SEDANG

In [5]:
ispu_2024

,periode_data,bulan,tanggal,stasiun,pm_sepuluh,pm_duakomalima,sulfur_dioksida,karbon_monoksida,ozon,nitrogen_dioksida,max,parameter_pencemar_kritis,kategori
0,202401,1,21,DKI3 Jagakarsa,51.0,65.0,45.0,9.0,8.0,79.0,79.0,NaN,SEDANG
1,202401,1,22,DKI3 Jagakarsa,27.0,34.0,45.0,5.0,8.0,56.0,56.0,NaN,SEDANG
2,202401,1,23,DKI3 Jagakarsa,NaN,52.0,46.0,6.0,9.0,51.0,52.0,PM25,SEDANG
3,202401,1,24,DKI3 Jagakarsa,46.0,65.0,46.0,8.0,9.0,38.0,65.0,PM25,SEDANG
4,202401,1,25,DKI3 Jagakarsa,37.0,55.0,47.0,7.0,11.0,28.0,55.0,PM25,SEDANG
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1825,202412,12,27,DKI5 Kebon Jeruk Jakarta Barat,NaN,55.0,27.0,9.0,30.0,12.0,55.0,PM25,SEDANG
1826,202412,12,28,DKI5 Kebon Jeruk Jakarta Barat,NaN,40.0,26.0,6.0,30.0,12.0,40.0,PM25,BAIK
1827,202412,12,29,DKI5 Kebon Jeruk Jakarta Barat,NaN,51.0,32.0,8.0,28.0,11.0,51.0,PM25,SEDANG
1828,202412,12,30,DKI5 Kebon Jeruk Jakarta Barat,NaN,34.0,9.0,5.0,38.0,8.0,38.0,O3,BAIK
1829,202412,12,31,DKI5 Kebon Jeruk Jakarta Barat,NaN,26.0,9.0,3.0,26.0,3.0,26.0,PM25,BAIK

In [6]:
ispu_2025

,periode_data,bulan,tanggal,stasiun,pm_sepuluh,pm_duakomalima,sulfur_dioksida,karbon_monoksida,ozon,nitrogen_dioksida,max,parameter_pencemar_kritis,kategori
0,202504,4,24,DKI5 Kebon Jeruk,16.0,50.0,18.0,3.0,16.0,4.0,50.0,PM25,BAIK
1,202504,4,25,DKI5 Kebon Jeruk,23.0,81.0,19.0,9.0,24.0,3.0,81.0,PM25,SEDANG
2,202504,4,26,DKI5 Kebon Jeruk,30.0,77.0,20.0,11.0,29.0,3.0,77.0,PM25,SEDANG
3,202504,4,27,DKI5 Kebon Jeruk,31.0,85.0,21.0,12.0,47.0,4.0,85.0,PM25,SEDANG
4,202504,4,28,DKI5 Kebon Jeruk,24.0,78.0,20.0,9.0,37.0,4.0,78.0,PM25,SEDANG
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,202508,8,31,DKI3 Jagakarsa,28.0,60.0,53.0,8.0,19.0,39.0,60.0,PM25,SEDANG
1211,202508,8,1,DKI4 Lubang Buaya,63.0,89.0,30.0,7.0,28.0,16.0,89.0,PM25,SEDANG
1212,202508,8,2,DKI4 Lubang Buaya,73.0,105.0,31.0,11.0,25.0,21.0,105.0,PM25,TIDAK SEHAT
1213,202508,8,3,DKI4 Lubang Buaya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIDAK ADA DATA
1214,202508,8,4,DKI4 Lubang Buaya,63.0,84.0,27.0,14.0,26.0,26.0,84.0,PM25,SEDANG

## Explaratory and Data Analysis

### Dataset info

In [7]:
print(f"INFO Data ISPU 2023: \n {ispu_2023.info()}\n")
print(f"INFO Data ISPU 2024: \n {ispu_2024.info()}\n")
print(f"INFO Data ISPU 2025: \n {ispu_2025.info()}\n")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   periode_data               1825 non-null   int64
 1   tanggal                    1825 non-null   object
 2   stasiun                    1825 non-null   object
 3   pm_sepuluh                 1825 non-null   object
 4   pm_duakomalima             1825 non-null   object
 5   sulfur_dioksida            1825 non-null   object
 6   karbon_monoksida           1825 non-null   object
 7   ozon                       1825 non-null   object
 8   nitrogen_dioksida          1825 non-null   object
 9   max                        1825 non-null   object
 10  parameter_pencemar_kritis  1812 non-null   object
 11  kategori                   1825 non-null   object
dtypes: int64(1), object(11)
memory usage: 171.2+ KB
INFO Data ISPU 2023:
 None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1830 entries, 0 to 1829
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   periode_data               1830 non-null   int64
 1   bulan                      1830 non-null   int64
 2   tanggal                    1830 non-null   int64
 3   stasiun                    1830 non-null   object
 4   pm_sepuluh                 1718 non-null   float64
 5   pm_duakomalima             1810 non-null   float64
 6   sulfur_dioksida            1821 non-null   float64
 7   karbon_monoksida           1818 non-null   float64
 8   ozon                       1821 non-null   float64
 9   nitrogen_dioksida          1804 non-null   float64
 10  max                        1825 non-null   float64
 11  parameter_pencemar_kritis  1784 non-null   object
 12  kategori                   1830 non-null   object
dtypes: float64(7), int64(3), object(3)
memory usage: 186.0+ KB
INFO Data ISPU 2024:
 None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1215 entries, 0 to 1214
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   periode_data               1215 non-null   int64
 1   bulan                      1215 non-null   int64
 2   tanggal                    1215 non-null   int64
 3   stasiun                    1215 non-null   object
 4   pm_sepuluh                 1141 non-null   float64
 5   pm_duakomalima             1182 non-null   float64
 6   sulfur_dioksida            1171 non-null   float64
 7   karbon_monoksida           1183 non-null   float64
 8   ozon                       1181 non-null   float64
 9   nitrogen_dioksida          1175 non-null   float64
 10  max                        1213 non-null   float64
 11  parameter_pencemar_kritis  1199 non-null   object
 12  kategori                   1215 non-null   object
dtypes: float64(7), int64(3), object(3)
memory usage: 123.5+ KB
INFO Data ISPU 2025:
 None

### Mengatasi Null Values

In [8]:
## Cek null values
print(f"null value ispu 2023: \n{ispu_2023.isna().sum()}\n")
print(f"null value ispu 2024: \n{ispu_2024.isna().sum()}\n")
print(f"null value ispu 2025: \n{ispu_2025.isna().sum()}\n")

null value ispu 2023:
periode_data                  0
tanggal                       0
stasiun                       0
pm_sepuluh                    0
pm_duakomalima                0
sulfur_dioksida               0
karbon_monoksida              0
ozon                          0
nitrogen_dioksida             0
max                           0
parameter_pencemar_kritis    13
kategori                      0
dtype: int64

null value ispu 2024:
periode_data                   0
bulan                          0
tanggal                        0
stasiun                        0
pm_sepuluh                   112
pm_duakomalima                20
sulfur_dioksida                9
karbon_monoksida              12
ozon                           9
nitrogen_dioksida             26
max                            5
parameter_pencemar_kritis     46
kategori                       0
dtype: int64

null value ispu 2025:
periode_data                  0
bulan                         0
tanggal                       0
stasiun                       0
pm_sepuluh                   74
pm_duakomalima               33
sulfur_dioksida              44
karbon_monoksida             32
ozon                         34
nitrogen_dioksida            40
max                           2
parameter_pencemar_kritis    16
kategori                      0
dtype: int64

In [9]:
## Mengatasi null values ispu_2023
ispu_2023['parameter_pencemar_kritis'] = ispu_2023['parameter_pencemar_kritis'].fillna(ispu_2023['parameter_pencemar_kritis'].mode()[0])
ispu_2023.isna().sum()

periode_data                 0
tanggal                      0
stasiun                      0
pm_sepuluh                   0
pm_duakomalima               0
sulfur_dioksida              0
karbon_monoksida             0
ozon                         0
nitrogen_dioksida            0
max                          0
parameter_pencemar_kritis    0
kategori                     0
dtype: int64

In [10]:
## Mengatasi null values ispu_2024
ispu_2024['pm_duakomalima'] = ispu_2024['pm_duakomalima'].fillna(ispu_2024['pm_duakomalima'].mean())
ispu_2024['pm_sepuluh'] = ispu_2024['pm_sepuluh'].fillna(ispu_2024['pm_sepuluh'].mean())
ispu_2024['sulfur_dioksida'] = ispu_2024['sulfur_dioksida'].fillna(ispu_2024['sulfur_dioksida'].mean())
ispu_2024['karbon_monoksida'] = ispu_2024['karbon_monoksida'].fillna(ispu_2024['karbon_monoksida'].mean())
ispu_2024['ozon'] = ispu_2024['ozon'].fillna(ispu_2024['ozon'].mean())
ispu_2024['nitrogen_dioksida'] = ispu_2024['nitrogen_dioksida'].fillna(ispu_2024['nitrogen_dioksida'].mean())
ispu_2024['max'] = ispu_2024['max'].fillna(ispu_2024['max'].mean())
ispu_2024['parameter_pencemar_kritis'] = ispu_2024['parameter_pencemar_kritis'].fillna(ispu_2024['parameter_pencemar_kritis'].mode()[0])


ispu_2024.isna().sum()

periode_data                 0
bulan                        0
tanggal                      0
stasiun                      0
pm_sepuluh                   0
pm_duakomalima               0
sulfur_dioksida              0
karbon_monoksida             0
ozon                         0
nitrogen_dioksida            0
max                          0
parameter_pencemar_kritis    0
kategori                     0
dtype: int64

In [11]:
## Mengatasi null values ispu_2025
ispu_2025['pm_duakomalima'] = ispu_2025['pm_duakomalima'].fillna(ispu_2025['pm_duakomalima'].mean())
ispu_2025['pm_sepuluh'] = ispu_2025['pm_sepuluh'].fillna(ispu_2025['pm_sepuluh'].mean())
ispu_2025['sulfur_dioksida'] = ispu_2025['sulfur_dioksida'].fillna(ispu_2025['sulfur_dioksida'].mean())
ispu_2025['karbon_monoksida'] = ispu_2025['karbon_monoksida'].fillna(ispu_2025['karbon_monoksida'].mean())
ispu_2025['ozon'] = ispu_2025['ozon'].fillna(ispu_2025['ozon'].mean())
ispu_2025['nitrogen_dioksida'] = ispu_2025['nitrogen_dioksida'].fillna(ispu_2025['nitrogen_dioksida'].mean())
ispu_2025['max'] = ispu_2025['max'].fillna(ispu_2025['max'].mean())
ispu_2025['parameter_pencemar_kritis'] = ispu_2025['parameter_pencemar_kritis'].fillna(ispu_2025['parameter_pencemar_kritis'].mode()[0])


ispu_2025.isna().sum()

periode_data                 0
bulan                        0
tanggal                      0
stasiun                      0
pm_sepuluh                   0
pm_duakomalima               0
sulfur_dioksida              0
karbon_monoksida             0
ozon                         0
nitrogen_dioksida            0
max                          0
parameter_pencemar_kritis    0
kategori                     0
dtype: int64

### Feature Engineering

#### Menyamakan fitur semua dataset lalu gabungkan menjadi df master

In [20]:
### Drop kolom bulan

ispu_2024.drop(columns=['bulan'], inplace=True)
ispu_2025.drop(columns=['bulan'], inplace=True)

In [23]:
### Merge dataset

df_master = pd.concat([ispu_2023,ispu_2024,ispu_2025])
df_master

,periode_data,tanggal,stasiun,pm_sepuluh,pm_duakomalima,sulfur_dioksida,karbon_monoksida,ozon,nitrogen_dioksida,max,parameter_pencemar_kritis,kategori
0,202302,2023-02-25,DKI5 Kebon Jeruk Jakarta Barat,35,-,13,12,31,18,35,PM10,BAIK
1,202302,2023-02-26,DKI5 Kebon Jeruk Jakarta Barat,23,-,14,9,32,11,32,O3,BAIK
2,202302,2023-02-27,DKI5 Kebon Jeruk Jakarta Barat,20,-,13,8,33,13,33,O3,BAIK
3,202302,2023-02-28,DKI5 Kebon Jeruk Jakarta Barat,30,-,21,11,28,18,30,PM10,BAIK
4,202303,2023-03-01,DKI1 Bunderan HI,38,44,50,8,19,27,50,3,BAIK
...,...,...,...,...,...,...,...,...,...,...,...,...
1210,202508,31,DKI3 Jagakarsa,28.0,60.0,53.0,8.0,19.0,39.0,60.0,PM25,SEDANG
1211,202508,1,DKI4 Lubang Buaya,63.0,89.0,30.0,7.0,28.0,16.0,89.0,PM25,SEDANG
1212,202508,2,DKI4 Lubang Buaya,73.0,105.0,31.0,11.0,25.0,21.0,105.0,PM25,TIDAK SEHAT
1213,202508,3,DKI4 Lubang Buaya,45.491674,70.71912,28.918873,13.568893,20.88061,25.985532,70.915911,PM25,TIDAK ADA DATA
1214,202508,4,DKI4 Lubang Buaya,63.0,84.0,27.0,14.0,26.0,26.0,84.0,PM25,SEDANG

#### Menggabungkan fitur dari dataset libur nasional dengan dataset master

In [19]:
data_libur = pd.read_csv('./libur-nasional/dataset-libur-nasional-dan-weekend.csv')
data_libur['tanggal'] = pd.to_datetime(data_libur['tanggal'])
data2023_2025 = data_libur[data_libur['tanggal'].dt.year >= 2023]
data2023_2025

        tanggal  is_holiday_nasional      nama_libur  is_weekend   day_name
4748 2023-01-01                    1  New Year's Day           1     Sunday
4749 2023-01-02                    0             NaN           0     Monday
4750 2023-01-03                    0             NaN           0    Tuesday
4751 2023-01-04                    0             NaN           0  Wednesday
4752 2023-01-05                    0             NaN           0   Thursday
...         ...                  ...             ...         ...        ...
5839 2025-12-27                    0             NaN           1   Saturday
5840 2025-12-28                    0             NaN           1     Sunday
5841 2025-12-29                    0             NaN           0     Monday
5842 2025-12-30                    0             NaN           0    Tuesday
5843 2025-12-31                    0             NaN           0  Wednesday

[1096 rows x 5 columns]